language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install -r requirements.txt


script: pytest tests/test_main.py

after_success:
  - coveralls
  - codecov

