language: python

python: 
	-3.7.0

cache: pip

install:
  - pip install -r requirements.txt

script:
  - pytest tests/ --cov=modules --cov-report 
term-missing

before_install:
  - pip install --user codecov

after_success:
  - coveralls
