language: python

python:
  - "3.3"
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install -r requirements.txt


script: python -m unittest tests/test_main.py

after_success:
  - coveralls
  - codecov

