language: python

python: 
	- 2.7
  - 3.6
  - 3.7

cache: pip

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
  - pip install codecov


script:
  - pytest tests/test_main.py

after_success:
  - coveralls
  - codecov
